brand: Sequr
brand_image: /logo.png
description: "A pragmatic Hugo theme for bloggers.  Based on the classic \"Hyde\" design by mdo."
keywords: TheGroundZero, poison, theme, hugo
favicon: /favicon.ico

dark_mode: true
hideToc: false

enableGlobalLanguageMenu: true

author:
  name: TheGroundZero
  url: https://github.com/TheGroundZero/poison

copyright:
  year: 2019
  copyright: '<a href="https://www.gnu.org/licenses/gpl-3.0.html" target="_blank" rel="external noopener">GPLv3</a>'

# Links to your socials.
social:
  - name: bluesky
    url: https://bsky.app/profile/sequr.be
    rel: me
  - name: mastodon
    url: https://mastodon-belgium.be/@TerraGloba
    rel: me
  - name: github
    url: https://github.com/TheGroundZero
    rel: me
  - name: twitter
    url: https://twitter.com/DezeStijn
    rel: me
  - name: kofi
    url: https://ko-fi.com/s4squatch

feeds:
  rss:
    icon: false
  atom:
    icon: true

style:
  # Hex colors for your sidebar.
  moon_sun_background_color: "#515151"   # default is #515151
  moon_sun_color: "#FFF"                 # default is #FFF
  sidebar_a_color: "#FFF"                # default is #FFF
  sidebar_bg_color: "#202020"            # default is #202020
  sidebar_h1_color: "#FFF"               # default is #FFF
  sidebar_img_border_color: "#515151"    # default is #515151
  sidebar_p_color: "#909090"             # default is #909090
  sidebar_socials_color: "#FFF"          # default is #FFF

  # Hex colors for your content in light mode.
  code_color: "#000"                     # default is #000
  code_background_color: "#E5E5E5"       # default is #E5E5E5
  code_block_color: "#FFF"               # default is #FFF
  code_block_background_color: "#272822" # default is #272822
  content_bg_color: "#FAF9F6"            # default is #FAF9F6
  date_color: "#515151"                  # default is #515151
  link_color: "#268BD2"                  # default is #268BD2
  list_color: "#5A5A5A"                  # default is #5A5A5A
  post_title_color: "#303030"            # default is #303030
  table_border_color: "#E5E5E5"          # default is #E5E5E5
  table_stripe_color: "#F9F9F9"          # default is #F9F9F9
  text_color: "#222"                     # default is #222

  # Hex colors for your content in dark mode
  code_color_dark: "#FFF"                        # default is #FFF
  code_background_color_dark: "#515151"          # default is #515151
  code_block_color_dark: "#FFF"                  # default is #FFF
  code_block_background_color_dark: "#272822"    # default is #272822
  content_bg_color_dark: "#121212"               # default is #121212
  date_color_dark: "#9A9A9A"                     # default is #9A9A9A
  link_color_dark: "#268BD2"                     # default is #268BD2
  list_color_dark: "#9D9D9D"                     # default is #9D9D9D
  post_title_color_dark: "#DBE2E9"               # default is #DBE2E9
  table_border_color_dark: "#515151"             # default is #515151
  table_stripe_color_dark: "#202020"             # default is #202020
  text_color_dark: "#EEE"                        # default is #EEE
